# Generated by Django 3.2.16 on 2023-09-04 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20230904_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='slug',
            field=models.TextField(blank=True, null=True),
        ),
    ]
