# Generated by Django 3.2.16 on 2023-09-07 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20230907_1815'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='~user=following',
        ),
    ]
