# Generated by Django 3.2.16 on 2023-09-07 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_follow_~user=following'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
    ]
