# Generated by Django 3.2.16 on 2023-09-07 12:23

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_alter_post_options'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='~user=following',
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.CheckConstraint(check=models.Q(('user', django.db.models.expressions.F('following')), _negated=True), name='user_not_self_follow'),
        ),
    ]
